### PR TITLE
Dialog docs, improvements

### PR DESCRIPTION
**Pull request by mischnic**
- Sort side alphabetically (mostly)
- Add page about dialogs
- Add a list of classes to the long AttributedString page

### CODE REVIEW

**Comment by parro-it** [comment]
> Maybe we should change AppVeyor so that it doesn't fails if the token is missing (so that it behaves like Travis).

Yes, it could be useful.

**Comment by mischnic** [comment]
I think
```
if defined NOW_TOKEN (
```

would be more useful. If your tagging a commit with a failing test is failing it's already too late.

**Comment by parro-it** [comment]
Yes, it's better...

**Comment by parro-it** [comment]
Look fine now... going to merge

**Comment by parro-it** [comment]
The node 6 test is failing, but since the snapshots are not published, we can not see what the problem is.

An idea I have for this use case is to build a tool that write a comment in the pull request containing the offending tests snapshot images.

What do you think? Too difficult to do?

**Comment by mischnic** [comment]
>  The node 6 test is failing, but since the snapshots are not published, we can not see what the problem is.

Now it isn't anymore 🤔 . Sometimes it's the area-scrolling, sometimes notepad.

> An idea I have for this use case is to build a tool that write a comment in the pull request containing the offending tests snapshot images.What do you think? Too difficult to do?

I like that idea - as currently done by some Code Coverage tools. But still the same problem: how do you authenticate with Github? Using a token... ah

**Comment by parro-it** [comment]
> I like that idea - as currently done by some Code Coverage tools. But still the same problem: how do you authenticate with Github? Using a token... ah

😢 you're right, we are in a loop... another option could be to publish a site to now where we can upload images (without any authentication), and it then take cares of publish it to the PR. This way we don't leak the GH token; anyone could post images to any PR using this services, but that's all.
And anyway, you can publish any image to any PR anyway, just using your account...

**Comment by mischnic** [comment]
> you're right, we are in a loop... another option could be to publish a site to now where we can upload images (without any authentication), and it then take cares of publish it to the PR. This way we don't leak the GH token; anyone could post images to any PR using this services, but that's all.
And anyway, you can publish any image to any PR anyway, just using your account...

I'll look into that.

**Comment by mischnic** [comment]
This is a test comment

**Comment by mischnic** [comment]
This is a test comment

**Comment by mischnic** [comment]
This is a test comment

**Comment by mischnic** [comment]
# screenshot-tester report

**Comment by mischnic** [comment]
🎉 

Issued just by executing:
```
curl -F "core-api=@/.../hugin.png" -F "controlgallery=@/.../hugin.png" https://screenshot-tester-server.now.sh/parro-it/libui-napi/42
```

Will continue tomorrow.

**Comment by mischnic** [comment]
*this comment was created by screenshot-tester-server*
# screenshot-tester report



*This comment was created automatically by screenshot-tester-server.*

**Comment by mischnic** [comment]
# screenshot-tester report




*This comment was created automatically by screenshot-tester-server.*

**Comment by mischnic** [comment]
# screenshot-tester report




*This comment was created automatically by screenshot-tester-server.*

**Comment by parro-it** [comment]
Wow, that's really impressive!

**Comment by mischnic** [comment]
> Wow, that's really impressive!

Thank you! Constraints: 1 GB bandwidth limit for Now & 500mb max of storage space for database (= the screenshots).
Only thing missing: differentiation of multiple OSs

**Comment by mischnic** [comment]
# screenshot-tester report

(The *D* link in the rightmost column opens a diff)


### Windows
[Overview](https://screenshot-tester-server.now.sh/parro-it/libui-napi/42/0/win/index.html)

<b>All tests passed</b>
<summary>Passed tests:</summary>
<details>
<table>
	<tr>
		<td>Reference</td>
		<td>Result</td>
	</tr>

<tr><td></td><td></td><td><a target="_blank" href="https://screenshot-tester-server.now.sh/parro-it/libui-napi/42/0/win/temp/area-adv.js_diff.png">D</a></td></tr>
<tr><td></td><td></td><td><a target="_blank" href="https://screenshot-tester-server.now.sh/parro-it/libui-napi/42/0/win/temp/forms.js_diff.png">D</a></td></tr>
<tr><td></td><td></td><td><a target="_blank" href="https://screenshot-tester-server.now.sh/parro-it/libui-napi/42/0/win/temp/grid.js_diff.png">D</a></td></tr>
<tr><td></td><td></td><td><a target="_blank" href="https://screenshot-tester-server.now.sh/parro-it/libui-napi/42/0/win/temp/node-pad.js_diff.png">D</a></td></tr>
<tr><td></td><td></td><td><a target="_blank" href="https://screenshot-tester-server.now.sh/parro-it/libui-napi/42/0/win/temp/text.js_diff.png">D</a></td></tr>
</table>
</details>
<br>
<br>

*This comment was created automatically by screenshot-tester-server.*

**Comment by parro-it** [comment]
> Thank you! Constraints: 1 GB bandwidth limit for Now & 500mb max of storage space for database (= the screenshots).

Doesn't seems to much space... does the limits go away with a paying subscription?

**Comment by mischnic** [comment]
> Doesn't seems to much space... does the limits go away with a paying subscription?

Right now I'm using the https://mlab.com/ free plan. 500mb / max 4mb per PR = 125 PRs (that'd be full sets for latest node on each platform and only the failing tests for the rest).

Possible solutions:
- Restructure architecture to use static now deployments and link them all with the comment in the database
- if not enough space: delete oldest data

**Comment by mischnic** [comment]
Any suggestions? https://github.com/mischnic/screenshot-tester/pull/9#issuecomment-396160539

**Pull request merged**
