### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by mischnic**
Changes:
- grouped tests in `test_errors.js` (as much as possible), didn't change tests using because it didn't quite understand that function and how to not use `t.end()` in it
- format tape output with tap-spec
- make the `check_c_tests.run_tests` output tap compliant
- use own assert macro so that all tests run
- napi_utils.h: removed `\n` because it interfered with tap-spec (it is now also consistent with node error messages):

```
TypeError: Argument has_menubar: A boolean was expected

    at new UiWindow (/Users/niklas/Desktop/DEV-TEST/libui/libui-napi/js/window.js:21:24)
    at Object.<anonymous> (/Users/niklas/Desktop/DEV-TEST/libui/libui-napi/example/forms.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
```
-->
```
TypeError: Argument has_menubar: A boolean was expected
    at new UiWindow (/Users/niklas/Desktop/DEV-TEST/libui/libui-napi/js/window.js:21:24)
    at Object.<anonymous> (/Users/niklas/Desktop/DEV-TEST/libui/libui-napi/example/forms.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
```

### CODE REVIEW

**Comment by mischnic** [comment]
Are these equivalent?
```js
runAsync(t, startLoop, () => {
	const win = new UiWindow(null, 42, 42, true);
	t.throws(() => win.close(), /Close called on closed window./);
	return stopLoop();
});
```

```js
startLoop()
    .then(() => {
        const win = new UiWindow(null, 42, 42, true);
        t.throws(() => win.close(), /Close called on closed window./);
        return stopLoop();
    })
    .then(()=>t.end());
```

**Comment by parro-it** [comment]
Really nice:

image

(The failure was intentionally provoked)

This PR does not include yet the tests you wrote with screenshot-tester?

**Comment by mischnic** [comment]
> Will very soon

Pushed. You'll have to add your own NOW_TOKEN env variable to appveyor and travis.

**Comment by parro-it** [comment]
There is a reason why gui tests results are not in tap format?

image

**Comment by mischnic** [comment]
> There is a reason why gui tests results are not in tap format?

I haven't added custom log formatter capability to screenshot-tester (yet).

**Comment by parro-it** [comment]
We should set a common locale to run the tests, the date control correctly show the value in current machine locale:

image

Austria or Italia? 😀
Do you know what are AV and Travis locales?

**Comment by mischnic** [comment]
> We should set a common locale to run the tests, the date control correctly show the value in current machine locale:

👍  Yes, tests that fail during development and pass on CI are confusing.

> Austria or Italia? 😀
Do you know what are AV and Travis locales?

Decidi tu 😄.
I wasn't able to find a way to set the time/date format after a quick google search.

**Comment by mischnic** [comment]
> > There is a reason why gui tests results are not in tap format?
>
> I haven't added custom log formatter capability to screenshot-tester (yet).

Like this?
bildschirmfoto 2018-05-30 um 23 08 29

Should the html report be a "test" as well?

**Comment by parro-it** [comment]
Awesome!

> Should the html report be a "test" as well?

No, I don't think so.

**Comment by parro-it** [comment]
I set the NOW_TOKEN variable. But AV only decodes vars for commits on master branch.
On node 6 on travis there is a failure, but I cannot find the URL on now at which I can found failing results. Do you print it somewhere?

**Comment by mischnic** [comment]
> I set the NOW_TOKEN variable. But AV only decodes vars for commits on master branch.

Yes, because I could otherwise change the CI script in a PR to print out your token and I could take over your account (along those lines).

**Comment by parro-it** [comment]
I'm going to merge this so I can trigger the test process on CI. 

The localization problem could be solved later, I think it's a bit annoiyng, but we could for now manually set the local of our systems to the same of AV & travis when we run the tests.

**Comment by mischnic** [comment]
> The localization problem could be solved later, I think it's a bit annoiyng, but we could for now manually set the local of our systems to the same of AV & travis when we run the tests.

We could make it "optional" if not running on CI.

**Comment by parro-it** [comment]
> We could make it "optional" if not running on CI.

Great! 
There is some problem with the UiArea control on node 8 on Windows: https://snapshots-sqbvfgjgqz.now.sh/. Seems it's not rendering at all.

**Comment by parro-it** [comment]
This is an AWESOME test tool!

**Comment by mischnic** [comment]
> There is some problem with the UiArea control on node 8 on Windows: https://snapshots-sqbvfgjgqz.now.sh/. Seems it's not rendering at all.

Rerun the build, had that once as well.

**Comment by parro-it** [comment]
We should investigate it.
AV is downloading the ia32 version of the libui binary, it should be downloading the 64bit version.

**Comment by mischnic** [comment]
> AV is downloading the ia32 version of the libui binary, it should be downloading the 64bit version.

https://ci.appveyor.com/project/parro-it/libui-napi/build/1.0.384/job/a3nd09g6r0gyumbc:

It's also installing Node 32bit:
```
Installing Node.js v10.3.0 (x86)...

...

Downloaded zip: C:\Users\appveyor\.libui\libui-shared-windows-ia32-alpha3.5-master-003.tar.gz
Libui binaries extracted to: C:\projects\libui-napi
```

**Comment by parro-it** [comment]
I added now both the 32 & 64bit version of the tests:
https://ci.appveyor.com/project/parro-it/libui-napi/build/1.0.387

**Pull request merged**
