### PR TITLE
Node 6

### LINKED ISSUE #19: Add support for node 6
See discussion on #11

### PR DESCRIPTION
**Pull request by mischnic**
Closes #19 

- [x] remove await/async in tools
- [x] add to ci

### CODE REVIEW

**Comment by mischnic** [comment]
I also refactored functions used in both tools into a seperate file.

What would happen if CI ran with multiple node versions? Would they all get published (or multiple times)?

**Comment by parro-it** [comment]
> I also refactored functions used in both tools into a seperate file.

You rock!

> What would happen if CI ran with multiple node versions? Would they all get published (or multiple times)?

We can filter it:

https://github.com/mafintosh/a-napi-example/blob/c42058fdb2f3d8bc771fe5ac26a8264dd2d900eb/appveyor.yml#L32-L41

https://github.com/mafintosh/a-napi-example/blob/c42058fdb2f3d8bc771fe5ac26a8264dd2d900eb/.travis.yml#L24-L34

**Comment by mischnic** [comment]
> > I also refactored functions used in both tools into a seperate file.

Fun fact: while testing the download tools, I nearly `rm-rf-ed` my home folder while trying to delete the cache 😄 . I'll have to restore some dot files from my backup...

**Comment by parro-it** [comment]
> Fun fact: while testing the download tools, I nearly rm-rf-ed my home folder while trying to delete the cache 😄 . I'll have to restore some dot files from my backup...

Beware! We should rest more 🧐 
😆😆

**Comment by parro-it** [comment]
https://nodejs.org/api/n-api.html#n_api_napi_fatal_exception
https://nodejs.org/api/n-api.html#n_api_napi_open_callback_scope

We should remove that two functions... supported only from node >9

**Comment by parro-it** [comment]
> https://nodejs.org/api/n-api.html#n_api_napi_fatal_exception
https://nodejs.org/api/n-api.html#n_api_napi_open_callback_scope
> 
> We should remove that two functions... supported only from node >9

I'll take care of this, but cannot tonight... will do tomorrow

**Comment by parro-it** [comment]
Removed offending functions. 
Remove of callback_scope seem to have no observable effects.
But `napi_fatal_exception` is essential to trigger a useful uncaught exception.
By now, I replaced it with napi_fatal_error, but this . function call abort and brutally kill the process, so it is sub-optimal.
Maybe it's better to just write exception errors on stderr?

**Comment by parro-it** [comment]
More info here:
https://github.com/nodejs/node/issues/15371
https://github.com/nodejs/node/pull/14697

**Comment by parro-it** [comment]
Strangely enough, AppVeyor does not install node 6.14.2, it seems stick with 6.14.1

image

**Comment by parro-it** [comment]
Finally I was able to install the correct node 6 version on AV. Merging...

**Pull request merged**
