### PR TITLE
Fix new example test

### PR DESCRIPTION
**Pull request by mischnic**
Could you please try running `npm install` in the gallery folder?
npm is behaving strangely:

```
$ (cd example/gallery && npm install)
npm WARN gallery@0.0.0 No description
npm WARN gallery@0.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/Users/travis/build/mischnic/libui-napi/example/gallery/node_modules/.staging/fsevents-fc38b293/node_modules/abbrev' -> '/Users/travis/build/mischnic/libui-napi/example/gallery/node_modules/.staging/abbrev-de0bb022'
npm ERR! path /Users/travis/build/mischnic/libui-napi/example/gallery/node_modules/.staging/libui-napi-b83f006d/node_modules/@ava/.DS_Store
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/travis/build/mischnic/libui-napi/example/gallery/node_modules/.staging/libui-napi-b83f006d/node_modules/@ava/.DS_Store' -> '/Users/travis/build/mischnic/libui-napi/example/gallery/node_modules/.staging/@ava/.DS_Store-eecd2b6b'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/travis/.npm/_logs/2018-05-31T21_15_19_193Z-debug.log
/Users/travis/.travis/job_stages: line 57: shell_session_update: command not found
```

It seems to work only without a package lock file. But it creates one that is identical to the checked in file.

### CODE REVIEW

**Comment by mischnic** [comment]
No, in the CI script. It doesn't even get to the testing stage: https://travis-ci.org/parro-it/libui-napi/jobs/386378725#L2725

**Comment by parro-it** [comment]
I don't understand that log: what is the .staging folder?

**Comment by mischnic** [comment]
>what is the .staging folder?

npm downloads packages into that temp folder first.

Have you tried it out locally?

**Comment by parro-it** [comment]
> Have you tried it out locally?

Yes, the test pass.

**Comment by parro-it** [comment]
Ah, wait, it fail if I remove exmaple/gallery/node_modules folder.

**Comment by parro-it** [comment]
I removed the pkg lock file from git

**Pull request merged**
