### PR TITLE
Fix loop again

### PR DESCRIPTION
**Pull request by parro-it**
In this branch, I'll solve the problem to the closeLoop that emerges running tests in #23.
I also solve #6 and #7.

@mischnic since #23 is almost done except for tests, I purpose you to merge that and on open another PR for further area improvements. So we can merge this PR in master when I complete it independently of #23.

* [x] - fix closeLoop problem.
* [x] - introduce barrier to improve synchronization between threads.
* [ ] - ~try to replace uiLoopWakeup with uiQueueMain.~ _does not work_
* [ ] - control_gc called multiple times causeing a pointer being freed two times

### CODE REVIEW

**Comment by mischnic** [comment]
> I purpose you to merge

Go ahead and merge area. What about the "pointer being freed was not allocated" error?

**Comment by parro-it** [comment]
> Go ahead and merge area. 

👍🏻

> What about the "pointer being freed was not allocated" error?

It seems that for some reason either on_control_gc or control_on_destroy are called multiple times.
I'll take care of that here too

**Comment by parro-it** [comment]
I did some progress with this stuff. Tests now are passing also on AV and travis.

**Comment by mischnic** [comment]
Why does Travis say "test failed"? https://travis-ci.org/parro-it/libui-napi/jobs/383401178

**Comment by parro-it** [comment]
I'm seeing if it can be related to the double - free problem on area-adv.

**Comment by parro-it** [comment]
> I'm seeing if it can be related to the double - free problem on area-adv.

On macOS HS, I cannot reproduce the problem either in area-adv or on tester branch.

**Comment by mischnic** [comment]
> On macOS HS, I cannot reproduce the problem either in area-adv or on tester branch.

Sierra with `tester` branch: `yarn test` works fine for the first time. Second invocation:

```
ok 16 tests executed
# ui test
node(3238,0x7fffda4963c0) malloc: *** error for object 0x3000100000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called
*** error for object 0x3000100000000: pointer being freed was not allocated
 

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffd164cd42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fffd173a457 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fffd15b2420 abort + 129
3   libsystem_malloc.dylib        	0x00007fffd16a1fe7 free + 530
4   ui.node                       	0x0000000103e53c8a on_control_gc + 28 (control.c:48)
5   node                          	0x000000010003c73e (anonymous namespace)::v8impl::Reference::FinalizeCallback(v8::WeakCallbackInfo<(anonymous namespace)::v8impl::Reference> const&) + 90
6   node                          	0x000000010041a814 v8::internal::GlobalHandles::PendingPhantomCallback::Invoke(v8::internal::Isolate*) + 76
7   node                          	0x000000010041acfd v8::internal::GlobalHandles::DispatchPendingPhantomCallbacks(bool) + 119
8   node                          	0x000000010041af28 v8::internal::GlobalHandles::PostGarbageCollectionProcessing(v8::internal::GarbageCollector, v8::GCCallbackFlags) + 44
9   node                          	0x000000010042a146 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) + 1508
```

**Comment by parro-it** [comment]
Could you try with this additional check I added?

**Comment by mischnic** [comment]
> Could you try with this additional check I added?

Works now. (I ran the test 4 times and it never crashed).

**Comment by parro-it** [comment]
Also, I think the only reason I commented the free of the handle itself was to just to check later if it was freed. But this cause a slight memory leak, because the handles are never freed.

**Comment by parro-it** [comment]
😭 it crashed again on travis

**Comment by parro-it** [comment]
It seems the way control_handle are directly freed in tests interfers with how we free in control.c.
Since it anyway it wasn't  the way they are supposed to be free, I remove the free calls from tests.

**Comment by parro-it** [comment]
I still can't reproduce the problem on tester branch, but anyway I'm going to merge this PR, we can fix that problem in tester branch if it persist...

**Pull request merged**
