### PR TITLE
Organize sidebar into categories

### PR DESCRIPTION
**Pull request by mischnic**
Preview: https://mischnic.github.io/libui-napi/#/

### CODE REVIEW

**Comment by parro-it** [comment]
Really good!

**Comment by mischnic** [comment]
In the docs, they are sometimes called widgets and sometimes controls...

**Comment by parro-it** [comment]
I'm trying to call them controls everywhere. Seems more used?

**Comment by parro-it** [comment]
I contradicted myself and created a GH-Pages so we can preview changes: https://parro-it.github.io/libui-napi/

**Pull request merged**
